version: '1' 
services:
  db:
    container_name: postgresdb-curso
    image: postgres:15.5-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4-curso
    image: dpage/pgadmin4:8.1
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN4_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN4_PASS}
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
      - ./pgadmin4:/certs/server.cert
      - ./pgadmin4:/certs/server.key
      - ./pgadmin4:/pgadmin4/servers.json